version: '3'

services:

  mysql:
    image: mysql:5.7.20
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - 3306

  backend-php:
    build:
      context: ./backend/
      dockerfile: config/docker/php/prod/Dockerfile
    depends_on:
      - mysql

  backend-nginx:
    build:
      context: ./backend/
      dockerfile: config/docker/nginx/Dockerfile
    depends_on:
      - backend-php
    ports:
      - 8080:80

  frontend-node:
    build:
      context: ./frontend/
      dockerfile: config/docker/node/Dockerfile
    user: "node"
    working_dir: /home/node
    environment:
      - NODE_ENV=production
    command: "npm start"
    expose:
      - 3000
    ports:
      - 3000:3000

volumes:
  mysql-data: